### PR TITLE
Release notes

### PR DESCRIPTION
**Pull request by hannesa2**
same like #337

### CODE REVIEW

**Comment by emartynov** [comment]
Hi Hanness, So you didn't wait for the PR. Sorry I was distracted.

**Comment by hannesa2** [comment]
No problem, but all becomes more a mess, the more I do.
I created `3.0.6`, because `3.0.5` showed me no release, but `3.0.6` shows me no diff to `3.0.5`

So I stop now, because all is fine.

Anyway, this is a cool feature and I will see it next time when a release will be created

**Comment by emartynov** [comment]
I see two warnings here https://github.com/MikeOrtiz/TouchImageView/actions/runs/694978172

**Comment by emartynov** [comment]
Oke

**Pull request merged**
