### PR TITLE
Added gradle build file

### PR DESCRIPTION
**Pull request by jitpack-io**
To make it easier building from command line and on https://jitpack.io

### CODE REVIEW

**Comment by ThirtyOne34** [comment]
Yes, please!

**Comment by ligi** [comment]
As this was not merged for over a year I now released a version via @jitpack-io here: https://jitpack.io/#ligi/touchimageview/2.1
There I was also separating library and example so you have no example code in the library aar

**Comment by uDevel** [comment]
@ligi Can you send a link to your fork or repo with license so people can use it?
Without a repo or licence, it's hard for people to attribute and use it.

**Comment by ligi** [comment]
@uDevel not sure what you mean - I kept the original LICENSE - no change there

**Comment by ligi** [comment]
the repo is here: https://github.com/ligi/TouchImageView
on top you find information on how to get it via jitpack

**Comment by uDevel** [comment]
Thank you very much.
Exactly what I need.

**Comment by ligi** [comment]
you are welcome

**Comment by hannesa2** [comment]
Last master has already such a file now. If you miss something please make a new PR

**Pull request closed without merging**
