### PR TITLE
Added animated zoom functionality

### PR DESCRIPTION
**Pull request by batzner**
I use the TouchImageView for a map in a game. I needed to smoothly zoom across the map, so I added the functionality to set the zoom and the target focus with a linear animation.

### CODE REVIEW

**Comment by Rskut** [comment]
Hello, the animated zoom functionality works perfectly but I need the scaletype as parameter like in the orginal setZoom function. Could you tell me how I can add it?

**Comment by hannesa2** [comment]
This repo is dead, when you make your PR in this [fork](https://github.com/hannesa2/TouchImageView), I will merge it immediate

**Comment by hannesa2** [comment]
Last master has changed a lot, please double check if your PR still makes some improvements. 
Doing so, please rebase it, or if you are happy, please close this one

**Comment by hannesa2** [comment]
Because this PR isn't merge-able, I applied it with #218

**Pull request closed without merging**
