### PR TITLE
Revert "SetZoom update the method to calculate the trans"

### PR DESCRIPTION
**Pull request by hannesa2**
This reverts commit bc7b5069f6287b8797765ce4d56fc6dac947c175.

### CODE REVIEW

**Comment by hannesa2** [comment]
close #507

**Comment by hannesa2** [comment]
As expected the zoom is now different (thanks to #513 the CI do a verification)
image

@SimFG it reverts your pull request #329 and handles #507 and #506
To be honest, I don't know if I should revert it or not. What do you think @SimFG and @bartek-wesolowski

I'm open to any solution.

**Comment by hannesa2** [comment]
close #506

**Comment by hannesa2** [comment]
And it founds more differences https://github.com/MikeOrtiz/TouchImageView/suites/10513010901/artifacts/522001897
I think the screenshot comparison mechanism is not perfect and the init status is confusing too
image

**Comment by bartek-wesolowski** [comment]
I think reverting the commit is the right thing to do. The current formula is incorrect. If we want to block panning of smaller images if their containing view is bigger then we should probably adjust `getFixTrans()` instead of `setZoom()`.

**Review by bartek-wesolowski — APPROVED** [review]

**Pull request merged**
