### PR TITLE
Fix loading network pictures through Glide in ViewPager2

### PR DESCRIPTION
**Pull request by boboZeng**
修复在ViewPager2通过Glide加载网络图片无法显示问题

### CODE REVIEW

**Comment by hannesa2** [comment]
Sorry, I don't understand. Please show me a picture before and after this change.

**Comment by boboZeng** [comment]
image
```
        Glide.with(holder.imagePlace.context)
            .load(photoList[position])
            .into(holder.imagePlace)
```
gilde load imge no working

**Comment by hannesa2** [comment]
Thank you for your contribution.

Hmm, when I uses screenshot from a previous **A** pull request https://github.com/MikeOrtiz/TouchImageView/actions/runs/2715456740 and from your pull request **B**

### A
image

### B
image

Sorry, I see no improvement.
It would be super nice, when you can show before and after in a running example. Maybe here in this repo as a new test ?

**Comment by boboZeng** [comment]
```

        Glide.with(this)
            .load(GLIDE_IMAGE_URL)
            .into(object : CustomTarget<Drawable?>() {
                @SuppressLint("SetTextI18n")
                override fun onResourceReady(resource: Drawable, transition: Transition<in Drawable?>?) {
                    binding.imageGlide.setImageDrawable(resource)
                    binding.textLoaded.visibility = View.VISIBLE
                    binding.textLoaded.text = getString(R.string.loaded) + " within ${System.currentTimeMillis() - start} ms"
                    Log.d("GlideExampleActivity", binding.textLoaded.text as String)
                }

                override fun onLoadCleared(@Nullable placeholder: Drawable?) = Unit

            })
```
user CustomTarget is Not a good idea

**Comment by hannesa2** [comment]
I'm really open for any improvement, but currently it looks not like to be an improvement. (see screenshot)

> you change net image ,   no work

Sorry, I don't understand

**Comment by boboZeng** [comment]
ViewPage2
Glide.with(this) .load(GLIDE_IMAGE_URL) .into(binding.imageGlide)

you write ViewPage2 demo , then load network image

**Comment by hannesa2** [comment]
Indeed, Glide sample doesn't work, neither on master, (sorry to write that) nor you pull request https://github.com/boboZeng/TouchImageView/tree/bobozeng
image

image

**Comment by hannesa2** [comment]
image

**Comment by hannesa2** [comment]
For me the `master` is working, I see no issue
image

**Comment by shehramjamil** [comment]
> For me the `master` is working, I see no issue image

Try inside a viewPager and it failed to put the network image into imageView. 
Is this somewhat related to this?
https://github.com/MikeOrtiz/TouchImageView/issues/136

**Pull request closed without merging**
