### PR TITLE
Issue 325

### PR DESCRIPTION
**Pull request by hannesa2**
Your version with TouchImageview
image

with a normal ImageView
image

### CODE REVIEW

**Comment by hannesa2** [comment]
What's your desired layout and desired behavior ? Please with screenshot

**Comment by AlfaBravoX** [comment]
Firstly thanks a lot for your willingness to help. Let say, that NestedScrollView is not necessarily to be used. I tested this with ScrollView as well and got same result. right, I am looking for option to make same layout as with normal ImageView and the sample (with a normal ImageView) you've created is exactly what i want. 

But BTW I  was also able to understand the philosophy behind the widget design. TouchImageView is behaving exactly same as image view used in Google Photos, where you have this white space too, until you zoom the image. After zooming the blank space is taken by scaled image. So if TouchImageView would be used in new view with and with one widget only, then it perfectly does its job. Problem starts - like in my case, when you are using multiple TouchImageViews or one with other widgets in one activity. It would be great to give coder an option to control widget height based on image aspect ratio , that would perfectly extend TouchImageView functionality and the widget would be very flexible. 

should i explain further ?

**Comment by hannesa2** [comment]
> should i explain further ?

No. 

For the first step I recommend to search for "matrix" in code, debug and improve. Let's see if you find a solution

**Comment by hannesa2** [comment]
First, I changed the demo to have a preview during design time

**Comment by hannesa2** [comment]
The main question is, why does the image occupy that much space vertical 

image

**Comment by AlfaBravoX** [comment]
True, main question is, why does the image occupy that much space vertical. I have done quick hack, which so far addresses this problem. I haven't fully go to all scenarios that should be addressing all images aspect ratios etc., but as start for me this works fine. 


```
DisplayMetrics dm;

private void shrinkTouchImageView(TouchImageView tiv , Bitmap bm){

        //lets first check display width and density, lest work with pixels
        int display_width = dm.widthPixels;
        float densityDpi = (dm.density);

        //lets check image bitmap size
        float bm_width = bm.getWidth() / densityDpi;
        float bm_height = bm.getHeight() / densityDpi;

        //for later to be used to scale view height, that occupy that much space vertically
        float scaleCoefficient = (bm_height / bm_width);

        //get LParams and scale the view, if using SCALE_XY, then scaled bitmap width must be same as display width 
        android.view.ViewGroup.LayoutParams layoutParams = tiv.getLayoutParams();
        layoutParams.height = (int) ((display_width ) * scaleCoefficient );
        tiv.setLayoutParams(layoutParams);
    }
```

**Comment by hannesa2** [comment]
I see you have a solution. When you have a common usable solution , your are warmly welcome to contribute.
I close this

**Pull request closed without merging**
