### PR TITLE
SetZoom update the method to calculate the trans

### PR DESCRIPTION
**Pull request by SimFG**
solve the issue #326

### CODE REVIEW

**Comment by hannesa2** [comment]
Cool 

Do you have  screenshot before and after this ? It would help me a lot !

**Comment by SimFG** [comment]
I have uploaded some pics in the branch SetZoomOptCheck.
The following picture is the origin pic.
<https://raw.githubusercontent.com/SimFG/TouchImageView/SetZoomOptCheck/origin.jpg>
the following picture is the pic that calls setZoom(1.1f, 0f, 0f) before I update the 'setZoom' method to calculate the trans.
<https://raw.githubusercontent.com/SimFG/TouchImageView/SetZoomOptCheck/zoom_origin.jpg>
the following picture is the pic that calls setZoom(1.1f, 0f, 0f) after I update the 'setZoom' method to calculate the trans.
<https://raw.githubusercontent.com/SimFG/TouchImageView/SetZoomOptCheck/zoom_opt.jpg>

**Comment by hannesa2** [comment]
Thank you !

Btw, did you know, that you can copy&paste picture direct here ?

**Comment by SimFG** [comment]
wow, cool. I have tried it. Always, I only read some codes in the site. So, I don't know it. Thank you !

**Comment by hannesa2** [comment]
This is the current master and I don't see your problem. 
 
https://raw.githubusercontent.com/SimFG/TouchImageView/SetZoomOptCheck/zoom_origin.jpg
Do I need more then an other resolution. eg code changes ?

https://user-images.githubusercontent.com/3314607/110085622-9ba5db00-7d91-11eb-92d3-88c44896bae3.mp4

**Comment by SimFG** [comment]
I have changed the scaleType property to The center for seeing the trans clearly.

**Comment by SimFG** [comment]
I add a click listener for the imageSingle in the file 'SingleTouchImageViewActivity.kt'.
```
binding.imageSingle.setOnClickListener {
            binding.imageSingle.setZoom(1.1f, 0f, 0f)
        }
```

**Comment by hannesa2** [comment]
Ahhh, I got it 

In `AnimateZoomActivity` I did `binding.imageSingle.setZoom(1.1f, 0f, 0f)`
Before:
image

After:
image

That's why I request always a running example to save my time. 
I do this maintenance in my spare time for someone else.

**Comment by SimFG** [comment]
Cool, I am very excited because this is my first time contributing code.

**Comment by hannesa2** [comment]
I added the missing verification https://github.com/MikeOrtiz/TouchImageView/commit/1e51bb184dd352a5fc8a6b9b7a86c45451d37ed4

**Comment by hannesa2** [comment]
> Cool, I am very excited because this is my first time contributing code.

😎

You are a luck guy, it's not normal to get the first time a pull request done in 2h and a new release.
Sometimes I wait > 1 year or get never any response

**Comment by SimFG** [comment]
wow, it's amazing

**Pull request merged**
