### PR TITLE
Add shape outlined image example

### PR DESCRIPTION
**Pull request by emartynov**
As promised!

Here is an example of how to change border shape with the Outline.

Please review!

## Changes
* Add launch of the activity with new example
* Show how to round corners with Outline
* Add screenshot test

## Screenshot

Screenshot_1615891594

### CODE REVIEW

**Comment by hannesa2** [comment]
❤️
When you add additionally a smoketest with a screenshot, it would be perfect !
eg https://github.com/MikeOrtiz/TouchImageView/blob/master/app/src/androidTest/java/info/touchimage/demo/MainSmokeTest.kt#L42-L47

**Comment by emartynov** [comment]
I can not find the reference screenshots for it. Does it take first as a reference and saves it in the build cache?

**Comment by emartynov** [comment]
BTW, I don't know why but your code style is missing XML formatting - it took me some time to not introduce a lot of noise in the xmls.

**Comment by hannesa2** [comment]
> I can not find the reference screenshots for it. Does it take first as a reference and saves it in the build cache?

Sorry, currently it makes only the screenshot as artifact in github pull request. eg 
image

The compare mechanism is not finished ...

**Comment by emartynov** [comment]
Added test, let's wait for the result

**Comment by hannesa2** [comment]
I guess the `ScrollView` comes with some impacts, eg

image

This is your new one 
image

**Comment by emartynov** [comment]
Scroll view was added to the main screen only.

**Comment by emartynov** [comment]
I think the screenshot is taken to fast that the animation of the navigation is not yet finished.

**Review by hannesa2 — APPROVED** [review]

**Comment by hannesa2** [comment]
@emartynov You can merge it. Thank you !

**Comment by emartynov** [comment]
Great! I'm not a collaborator, so I don't have such a button :) I don't have any changes - you're free to merge whenever you have time.

**Pull request merged**
